apiVersion: apps/v1
kind: Deployment
metadata:
  name: phoenix
  namespace: chatbot
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: phoenix
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 1Gi
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: phoenix
