apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chatbot

resources:
  - ../../base

patches:
  - path: phoenix-deployment-patch.yaml
    target:
      kind: Deployment
      name: phoenix
  - path: couchdb-statefulset-patch.yaml
    target:
      kind: StatefulSet
      name: couchdb
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: chatbot-ingress
